name: apiverve_globalstockmarket
description: Global Stock Market is a tool for comparing stock market performance across 36 countries. It returns a normalized share price index (2015=100) from OECD data, allowing you to compare market growth between countries over time.
version: 1.1.14
homepage: https://apiverve.com/marketplace/globalstockmarket?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/globalstockmarket-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
